### ISSUE TITLE
Issue when user token is refreshed

### ISSUE THREAD

**Issue by avallete** [auth0-samples/auth0-ionic-samples#235]
Hi there,

Thank's for this example.

Trying to implement the same logic into my app I ran into an error similar to the one mentioned here: https://community.auth0.com/t/auth0-app-id-doesnt-link-with-the-android-application/67288

Looking into the details, it seems that the error occurs when the id_token is no longer valid, which seems to trigger a "getTokenFromIFrame" function, getting us out of the native "Browser" context causing the app to be stuck on the loading page.

<img width="996" alt="Screenshot 2022-07-04 at 19 56 26" src="https://user-images.githubusercontent.com/8771783/177203276-faddfc31-86ad-47ef-a6dc-219f19086a5c.png">

Anyone had a similar error before ?

Edit:

I've found those issues on the auth0 community forum, they seems to face the same issue:

https://community.auth0.com/t/auth0-app-id-doesnt-link-with-the-android-application/67288
https://community.auth0.com/t/silent-authentication-fails-on-capacitor-app-with-error-the-specified-redirect-uri-does-not-have-a-registered-origin/74440

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @avallete, unfortunately your issue fell through the cracks. There was [a solution](https://community.auth0.com/t/auth0-app-id-doesnt-link-with-the-android-application/67288/7) posted in the community forums, did you try this and did it work for you?

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you still need further support.
