### ISSUE TITLE
getTokenSilently results in login_required when requesting access token for second audience

### ISSUE THREAD

**Issue by austinheinrichs** [auth0-samples/auth0-ionic-samples#286]
Hello,

This may be similar to issue #235.

Using this sample repo, we were able to successfully authenticate to our app in an iOS emulator, however, we are having some trouble after the initial login.  Initially, we have our module configuration passing an audience.  In our case, we are using the angular SDK's AuthHttpInterceptor (https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.interceptor.ts) to retrieve a second access token for a different target audience shortly after the initial login.  Upon doing so, we get the generic error from Auth0 - login_required.  This works when using the web platform.  Checked configurations in Auth0 and everything seems okay there.  I saw some potential issues (not sure if its true or not) with the getTokenSilently methods fallback method of using an iframe when using capacitor so we also enabled/tried refresh tokens as well.  Same result there.  The most interesting this to me is that the silent auth failure in Auth0 doesn't have any user context attached even though the user$ observable is emitting.  Perhaps it is a prompt=none, interactive consent required issue?

The API call requiring the second access token is done after the user$ observable emits:
```
this.authService.user$.pipe(
      takeUntil(this.stopSubscriptions$),
      filter(u => u !== null),
      take(1))
      .subscribe((user) => {
        this.doMoreAfterLogin(user);
      });
```

Here is the module configuration:
```
AuthModule.forRoot({
      domain: environment.auth0.domain,
      clientId: environment.auth0.clientId,
      audience: 'urn:api:v2',
      cacheLocation: 'localstorage',
      httpInterceptor: {
        allowedList: [
          {
            uri: 'https://someuriacceptingv1audience/*',
            tokenOptions: {
              audience: urn:api:v1'
            }
          },
          'https://someuriacceptingv2audience/*'
        ]
      },
      redirectUri: redirectUri
    })
```

Our usage of the 'appUrlOpen' listener is the same as in the sample.  Any help you could provide would be greatly appreciated.

**Comment by frederikprijck** [comment]
When Auth0 gives you login_required, it means you need to initiate an interactive login by calling `loginWithRedirect` with the same audience as the one passed to `getTokenSIlently`, this is not something our SDK can do much about, it's Auth0 that is telling you it can not give you a token.

This is typical in such environments with multiple audiences, you want to ensure for every audience you atleast call `loginWithRedirect` once, ensure u get a Refresh Token and then the SDK will use that Refresh Token for any calls to `getTokenSilently`, which should not result in `login_required`. However, it could still happen that eventually the Refresh token expires and you get another `login_required` error, therefore it's advices in these kind of environmenbts to always catch `login_required` errors and react accordingly by calling `loginWithRedirect`.

**Comment by austinheinrichs** [comment]
@frederikprijck Thanks for the quick reply.  

loginWithRedirect()/loginWithPopup() doesn't appear possible in Capacitor due to the redirects between Safari and the app.  I believe that is why the sample references buildAuthorizeUrl() to callback explicitly to the app url.  I understand that login_required is indicative of an interactive login being required, however, the user had just authenticated and the configuration in Auth0 should allow for silent auth.  As I mentioned previously, it works fine when run in a browser unlike native iOS.  I guess I'm just looking to clarify the difference between the two.  Why does silent auth work fine in a browser, but the same flow requires interactive login from iOS?  Any insight would be greatly appreciated.

**Comment by frederikprijck** [comment]
This has to do with the fact that Silent Auth relies on cookies on the Auth0 domain and the fact that Capacitor's browser might handle these differently. You can overcome this using refresh tokens, but in order to be able to do that you will need to call `loginWithRedirect` (or in case of Capacitor, `buildAuthorizeUrl` and `Browser.open()`, followed by `handleRedirectCallback`).

That's a consequence of using multiple audiences, typically it could help to use a BFF / Gateway so that your SPA only talks to one audience and you don't have this issue / behavior.

**Comment by austinheinrichs** [comment]
@frederikprijck I had suspected it was Capacitor's handling of cookies that was causing this behavior, thank you for confirming.
I did find a workaround for now.  You can modify capacitor.config.json to whitelist navigation to your Auth0 domain and any enterprise connection domains you may be redirected to.  You also need to include a custom hostname to allow for the cookie to be shared.  In this example, my Auth0 domain would be identity.acme.com:
`
{
  ...
  "server": {
    "hostname": "mobile.acme.com",
    "allowNavigation": [
      "identity.acme.com",
      "{{Some enterprise connection domain host}}"
    ]
  }
}
`
