### ISSUE TITLE
Angular - iOS auth success, callback called, sample app does not process login

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0-samples/auth0-ionic-samples#441]
I’ve cloned this repo and am using the angular app.  I’ve configured auth.config.ts for my Auth0 app, both domain and clientId are properly set.  I’ve added the correct callback and logout urls to Auth0.

I’ve left capacitor.confg.ts alone, leaving appId as  'com.auth0.sample’.

Please correct me at this point if there are additional config instructions for this sample app I have overlooked.

I’m running on an iOS simulator v14.4.  I’ve additionally tried on iOS 16.2 with the same results.  The first issue is that the Safari browser remains open instead of properly being closed after login - probably not an Auth0 issue, but still something this sample app’s team needs be aware.  The second issue is that the sample app produces an error after receiving the auth0 callback.  Authorization does not appear to succeed and routing to profile does not happen.  The app remains on the Login page.

 The Xcode logs are as such:

⚡️  WebView loaded
⚡️  [log] - Angular is running in development mode. Call enableProdMode() to enable production mode.
⚡️  To Native ->  App addListener 45681863
⚡️  To Native ->  App addListener 45681864
⚡️  To Native ->  Browser open 45681865
2022-12-13 20:22:59.108576-0600 App[65759:2372650] Unbalanced calls to begin/end appearance transitions for <Capacitor.TmpViewController: 0x7fc82181cd50>.
⚡️  TO JS undefined
2022-12-13 20:22:59.709564-0600 App[65759:2372650] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
⚡️  TO JS {"url":"com.auth0.samples:\/\/xxxxx.us.auth0.com\/capacitor\/com.auth0.samples\/callback?code=kxknQWEblahblahblahblahZ0ndl0JMvoNRs1C&state=OTd5dEhfQ1dIblahblahblahblah80YTVxQw%3D%3D","iosSourceApplication":"com.apple.Saf
⚡️  [error] - ERROR {"isTrusted":true,"message":"Failed to fetch”}

Please help me understand why this sample app is not functioning.  I’m following the guide https://auth0.com/docs/quickstart/native/ionic-angular/interactive which led me to this repo.  BTW your guide is outdated and contains obvious bugs.

**Comment by frederikprijck** [comment]
Thanks for reaching out. 

I tried running the Angular sample using the following commands:

```
npm run build
npx cap run ios
```

This opens a working app, to which I can login and logout as expected.
If you are still experiencing issues, could you verify these issues also occur with the above commands?

If they do, could you share a bit more information for us to help resolve the issue?
