### ISSUE TITLE
Web Auth without handleRedirectCallback()

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0-samples/auth0-ionic-samples#446]
I’m baffled.....I’m attempting to use this repo to perform web auth.  It works fine, in fact a little too good.  I’ve noticed that commenting out the entire ngOnInit() method of app.component leaves the web authentication still functioning properly.  How is this possible?  handleRedirectCallback is never being called.  Please explain the web authentication flow as it relates to this sample code.  Thanks so much.

**Comment by frederikprijck** [comment]
Hey, handleRedirect is to only useful when you initially sign in.

As soon as you already signed in, we have the concept of silent authentication, which checks if you still have a session with Auth0 and handles things for you under the Hood.

So as long as the following conditions are met, we perform silent auth:

- user previously authenticated
- SDK is still included in the app
- the user hasn't logged out

As long as there is still An active session with Auth0 or you are using refresh tokens with local storage, on page load we will reinitialize authentication state for you.

**Comment by mikkimichaelis** [comment]
Ok, that makes sense.  I’ll test logging out then logging back in to verify handleLoginCallback() is called.

One question, it sounds like refresh tokens with local storage is activated by default for the web and authentication is taking place behind the scenes automatically on refresh.  However, I notice that on Android after logging in properly, when I close the app and reopen it I’m not automatically logged in ie. not using refresh tokens with local storage.  Can you point me in the right direction to enable that feature for device authentication please?

Thank you for your help!

**Comment by frederikprijck** [comment]
We do not activate refresh tokens or local storage by default, we rely on using iframes with third-party cookies by default.

Can you verify there are no errors in your Auth0 logs when running on Android? If not, please share a reproduction of the issue at hand for us to be able to investigate what could be causing this.

**Comment by frederikprijck** [comment]
Closing this, let me know if we can be of any further assistance.
