### ISSUE TITLE
Android App does not open after authentication

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0-samples/auth0-ionic-samples#475]
Yes, the sample provided when running on Android does automatically open after authentication.  What is missing is the reason why in your documentation.  Meaning I followed all the documentation to implement auth0/auth0-angular within my application and the Android app would not open.  I found that this repository contains within the [android/app/src/main/AndroidManifest.xml](https://github.com/auth0-samples/auth0-ionic-samples/blob/main/angular/android/app/src/main/AndroidManifest.xml) file the following additional lines

`<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
 </intent-filter>`

These lines are not automatically added when running ionic cap platform add android and are required for the proper use of auth0/auth0-angular (and probably react also).

I’m simply pointing this out for anybody else having issues implementing auth0-angular from scratch, or adding it to an existing project.  I do suggest updating the online [instructions](https://auth0.com/docs/quickstart/native/ionic-angular/interactive) and documentation regarding these samples and resources for implementing auth0-angular.

**Comment by frederikprijck** [comment]
Thanks, this has been called out in the docs:

![image](https://user-images.githubusercontent.com/2146903/213654095-96e2085a-db15-4795-bfc8-b7c146c5def5.png)

This links to information on how to configure it on iOS and Android, which elaborates about those 3 lines.
I agree, our quickstart does not just tell people to add these 3 lines, but it does tells them we assume you are using it, with links to relevant docs about it.

Could you elaborate on why that wouldn't be enough to cover the subject?

**Comment by mikkimichaelis** [comment]
Sure, a link to a very difficult Google doc is provided.  Thanks so much.  The reality though, is that a new developer or a hybrid developer with little experience with Android development would never come to the proper intent-filter required for your android lib to work properly.  I just wanted to post the proper snippet here such that another developer having the issue I mentioned could find the simple solution.

**Comment by RobLin72** [comment]
Mikki,
were you able to get the Android App login to work?
I click the login, enter in my credentials, app routs back to login page, 'isAuthenticated' is still false.
I updated the AndroidManifest.xml 
Any ideas why 'isAuthenticated' is not authenticating and being set to true?

**Comment by mikkimichaelis** [comment]
@RobLin72 I'm not sure in your case but I'll help as best I can to help you.  [auth0/auth0-angular](https://github.com/auth0/auth0-angular) (the package this sample is using for authentication) is working fine for me now, Android, iOS, and SPA.  Take a look at an [issue](https://github.com/auth0/auth0-angular/issues/405) I had over there first and see if that helps any.  That issue specifically dealt with isAuthenticated$ firing after a 60 sec delay upon returning to the Android app.

It sounds to me like auth0 is returning properly to your Android app, so this post is probably not revenant as this fixes the issue of Android app not opening after authentication takes place.

**Comment by mikkimichaelis** [comment]
This specific issue of the Android app not opening is best resolved using the documentation provided here https://capacitorjs.com/docs/apis/app#android (as mentioned by @ion-labs in another issue posted [here](https://github.com/auth0-samples/auth0-ionic-samples/issues/79).
