### ISSUE TITLE
Infinite loading on android phone

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-ionic-samples#49]
I have twice time: first time i've downloaded samples, replaced credentials, second time i've used `download sample` from auth0 tutorial. In both cases i've run `bower install && ionic state restore --plugins && ionic upload`. Using `Ionic View` on my Meizu m3 note  (Android 5.1) tested samples. In both cases got errors: (this one when i'm clicked on social provider icon: twitter, facebook, etc)
![s61004-232513](https://cloud.githubusercontent.com/assets/1114365/19091175/1f6c63b4-8a8a-11e6-9ec6-909f63e103a7.jpg)
Second one i've got when tried to relogin to database user:
![s61004-232435](https://cloud.githubusercontent.com/assets/1114365/19091176/1f86f436-8a8a-11e6-9b9c-a906315f6539.jpg)

**Comment by Amialc** [comment]
I've tried to reinstall `cordova-plugin-inappbrowser` as mentioned [here](https://github.com/auth0-samples/auth0-ionic-samples#lock-freezing-when-trying-to-do-social-login-or-logging-in-with-the-previously-logged-in-user), but it don't helped.

**Comment by chenkie** [comment]
fixed by adding `sso:false`
