### ISSUE TITLE
does not build after android directory remade

### ISSUE THREAD

**Issue by magwas** [auth0-samples/auth0-ionic-samples#496]
There are changes in the android config, which needed to get the application to run, but are not documented.
I reverse engineered it by deleting the android directory, remaking it by `npm run build; npx cap add android`, seeing the app being unable to catch the callback uri after authentication to auth0, and adding back changes until it worked again.

Probably this change should be documented, so others do not have to go through this journey.

Add a second intent-filter to `android/app/src/main/AndroidManifest.xml`

```
          <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="@string/custom_url_scheme" />
          </intent-filter>
```

**Comment by frederikprijck** [comment]
As mentioned earlier, we always are open to improve our documentation.

This has been called out on our [Quickstart](https://auth0.com/docs/quickstart/native/ionic-angular/01-login):

<img width="894" alt="image" src="https://user-images.githubusercontent.com/2146903/218694727-8568e567-bbea-4d97-83df-a71d8b60e47c.png">

We expect people to read those links to familiarize themselves with concepts they are using withing their application. Did you read the page linked there? If you did, can you help understand what isn't clear and what we can do to make this easier?

Keep in kind, we believe our quickstart is not the place to explain how Android Deep Links work, this is better left to Android experts and is why we link to the official documentation for that subject.

On top of that, our sample application comes pre configured to simplify the process for people trying to get up and running as fast as possible.
