### ISSUE TITLE
Repository is not working for Angular + Capacitor

### ISSUE THREAD

**Issue by deroux** [auth0-samples/auth0-ionic-samples#539]
Web-Browser redirect leaves to blank page
Mobile redirect returns 401 Unauthorized

**Comment by frederikprijck** [comment]
Thanks for reaching out. I tried running the Angular + Capacitor example on an Android emulator, and it works fine.

We will need additional information to be able to help determine what could be going wrong.

**Comment by frederikprijck** [comment]
You should be able to use a native application, that's what I tested with.

**Comment by deroux** [comment]
After I switch back to Native it works, didn't at the beginning.
