### ISSUE TITLE
outdated lock version

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-ionic-samples#60]
(AUTH-3926)
Some samples uses outdated auth0-lock version, for example [03-User-Profile](https://github.com/auth0-samples/auth0-ionic-samples/blob/master/03-User-Profile/bower.json#L5), [04-Linking-Accounts](https://github.com/auth0-samples/auth0-ionic-samples/blob/master/04-Linking-Accounts/bower.json#L5).

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
