### ISSUE TITLE
outdated angular-lock

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-ionic-samples#61]
(AUTH-3927)
Samples using outdated version of angular-lock and doesn't provide `oidcConformant` and `audience` parameter.

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
