### ISSUE TITLE
unauthorized error

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-ionic-samples#62]
(AUTH-4144)
After login, app tells me that [I'm not logged in](https://user-images.githubusercontent.com/1114365/28206571-205974b8-688f-11e7-8a39-eda26fe9d699.png).
![image](https://user-images.githubusercontent.com/1114365/28206586-26f48d6c-688f-11e7-8e27-86744672f1be.png)

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
