### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-ionic-samples#63]
(AUTH-4223)
Sample using outdated version of `angular-auth0` and other dependencies.

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects, where all dependencies have been updated. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
