### ISSUE TITLE
onRedirectUri not called

### ISSUE THREAD

**Issue by anmolarora1** [auth0-samples/auth0-ionic-samples#65]
After successful login, I am redirected to the app but the method 'Auth0Cordova.onRedirectUri' never really gets called. Tried passing callback to the Auth's login method and that too never gets called. Below is my code - 

$ionicPlatform.ready(function() {
    function handleUrl(url) {
      console.log('url - ', url');
      Auth0Cordova.onRedirectUri(url);
    }
    window.handleOpenURL = handleUrl;
});

// For the service 

    function login(callback) {
       var client = new Auth0Cordova(auth0Config);

       var options = {
           scope: 'openid profile offline_access'
       };

       client.authorize(options, function (err, authResult) {
           callback(true);
           if (err) {
               throw new Error(err);
           }
           if (authResult && authResult.accessToken && authResult.idToken) {
               setSession(authResult);
               $rootScope.$apply();
           }
       });
   }

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
