### ISSUE TITLE
App gets stuck after login

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-ionic-samples#66]
After authentication, the app gets stuck on the lock screen

![image](https://user-images.githubusercontent.com/15782359/34786574-e4a240e4-f60a-11e7-90d3-5e5b60c8359c.png)

**Comment by chpalatinus** [comment]
same here, not working on iOS devices

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback or are still seeing this issue with the new samples, please feel free to raise another ticket!
