### ISSUE TITLE
React  support

### ISSUE THREAD

**Issue by victororlyk** [auth0-samples/auth0-ionic-samples#68]
Currently there is no documentation on how to work with ionic/react + auth0;
There is no  good way to support Ionic React project.
Can you please give any advices on how to work with it ( without ionic/enterprise)

There is a plugin which can do some work when you will get into it. But it doesn't support openID
https://github.com/moberwasserlechner/capacitor-oauth2

Please give me some advices. Thank you in advance!

**Comment by stevehobbsdev** [comment]
This repo has now been updated with new samples for Ionic 5, Capacitor 3, and both React and Angular projects. If you have any feedback, please feel free to raise another ticket!
