### ISSUE TITLE
Capacitor login issue

### ISSUE THREAD

**Issue by djeter** [auth0-samples/auth0-ionic-samples#71]
Using the sample app provided for Capacitor/Angular, I am able to log in by pressing the login button which then opens a browser window.  However, when I am returned to the app, the login button is still there.  If I press it again, I see the logout button along with my user details.  It appears that the state is not being changed when you first log in.

**Comment by djeter** [comment]
I believe it has something to do with the Browser.Close().  Is there a workaround?

**Comment by stevehobbsdev** [comment]
Thanks for the report, I'm seeing this as well in some cases 👍🏻 let me investigate

**Comment by BetterAutomations** [comment]
The pull request partly fixed the problem. It resolved my issue where I kept only seeing Login, but now I have the issue @djeter raised; When I am returned to the app, the Login button is still there. If I press it again, I see the Logout button along with my user details.

**Comment by stevehobbsdev** [comment]
That's odd, the PR should have fixed that issue and I can no longer reproduce @djeter's issue with this fix. Are you literally just using the sample as-is without any changes?

**Comment by BetterAutomations** [comment]
Correct, no changes except what was in your most recent pull request. I uninstalled the app, rebooted the phone, reinstalled the app, same behavior.

**Comment by stevehobbsdev** [comment]
I've just tested this again and it's working correctly for me; not sure what else to suggest at this point.

**Comment by djeter** [comment]
@stevehobbsdev  To be clear, I was having this issue while testing on an Android device.

**Comment by BetterAutomations** [comment]
@djeter do you still see this issue after applying the pull request?

**Comment by stevehobbsdev** [comment]
Thanks @djeter, that's where I was also seeing the issue that should now be fixed.

**Comment by BetterAutomations** [comment]
Working now. I re-downloaded the tutorial code, deleted and restarted my local copy, and it's working now.
