### ISSUE TITLE
[SOLVED] native-run failed with error ERR_UNSUITABLE_API_INSTALLATION

### ISSUE THREAD

**Issue by BetterAutomations** [auth0-samples/auth0-ionic-samples#73]
Trying the [Ionic & Capacitor (Angular) tutorial](https://auth0.com/docs/quickstart/native/ionic-angular/01-login), and Android won't launch. I can successfully launch Android from another Ionic project on this computer, so I know my system is set up correctly. Google isn't clear what I need to do next. How can I resolve this?

To get to this point I clicked "Download sample," added the appropriate URLs to the application settings, unpacked it, ran `npm install`, `npm build`, `npm install @capacitor/android`.

```CBdeV@DAD-E5430 ~/auth0_ionic_test
$ npx cap run android
√ Copying web assets from www to android\app\src\main\assets\public in 4.33s
√ Creating capacitor.config.json in android\app\src\main\assets in 2.60ms
√ copy android in 4.41s
√ Updating Android plugins in 20.50ms
[info] Found 5 Capacitor plugins for android:
       @capacitor/app@1.0.3
       @capacitor/browser@1.0.3
       @capacitor/haptics@1.0.3
       @capacitor/keyboard@1.0.3
       @capacitor/status-bar@1.0.3
√ update android in 216.66ms
[error] native-run failed with error

        ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors


CBdeV@DAD-E5430 ~/auth0_ionic_test
$
```

**Comment by stevehobbsdev** [comment]
Thanks for raising this, do you think this is environmental? I am able to download the sample and use `npx cap run android` without any difficulty.

**Comment by BetterAutomations** [comment]
Unsure. `cap run` now works for me as well. Maybe I had to launch it once inside the Studio? Shrug.
