### ISSUE TITLE
Error 403: disallowed_useragent

### ISSUE THREAD

**Issue by BetterAutomations** [auth0-samples/auth0-ionic-samples#74]
Trying to get the [tutorial](https://auth0.com/docs/quickstart/native/ionic-angular/01-login) working. Using Android Studio 2020.3.1 Patch 2, Android emulator is a Pixel 5 running Android 11. Attempted to login with Google, the following error seen in [this screenshot](https://i.imgur.com/f9MJ3yk.png). Please assist.

**Comment by stevehobbsdev** [comment]
I'm not sure how to help here, this looks like something more specific to Ionic + Android than this sample. Is there something you can pin down within the sample that might cause this?

**Comment by BetterAutomations** [comment]
I have a [ticket opened as well](https://support.auth0.com/tickets/00503499) with Art S on the Auth0 team. Seems to be because Chrome is not installed by default in the emulator. Dragged in the .apk. Cannot validate that resolved the issue because that raised another issue: When I tap Login it temporarily goes to the Auth0 website then to localhost:4200 and Connection Refused. _Probably_ this is resolved, but I cannot validate it yet.

**Comment by BetterAutomations** [comment]
The localhost:4200 issue is (perhaps only temporarily) resolved (or worked around) by making the following change to /www/main.js. I say _perhaps temporarily_ because I believe this file gets overwritten when running `npm run build`. Seeking confirmation from Art.

```
      // Comment this out
      // const callbackUri = Object(_ionic_angular__WEBPACK_IMPORTED_MODULE_0__["isPlatform"])("desktop")
      //     ? "http://localhost:4200"
      //     : `${appId}://${auth0Domain}/capacitor/${appId}/callback`;
      // Replace with this
      const callbackUri = Object(_ionic_angular__WEBPACK_IMPORTED_MODULE_0__["isPlatform"])("desktop")
        ? `${appId}://${auth0Domain}/capacitor/${appId}/callback`
        : `${appId}://${auth0Domain}/capacitor/${appId}/callback`;
```

**Comment by stevehobbsdev** [comment]
It could be that `isPlatform` returns "desktop" on the emulator which is causing it to do the wrong thing, let me validate that

**Comment by stevehobbsdev** [comment]
Looks like my assumption was correct, and have corrected the example config in #78.

If you have copied the file for your own config, you will have to reflect the changes in there. The crux of the fix is using `isPlatform('ios') && isPlatform('android')` to detect the right platform.

Let me know if that helps.

**Comment by BetterAutomations** [comment]
No good for me. Still goes to localhost:4200. Strangely, the /www/main.js workaround above is also failing. I've re-run npm build, removed/reinstalled the app, no good.

**Comment by stevehobbsdev** [comment]
Are you able to send me a sample of what you're working with?

**Comment by BetterAutomations** [comment]
Working now. I was using [the tutorial](https://auth0.com/docs/quickstart/native/ionic-angular/01-login). Got it working by deleting the directory, re-downloaded it and re-applied your change to auth.config.ts. Your pull request is the only change made in the code. I know that and the main.js workaround above were the only changes made in the old code, so perhaps something was cached somewhere.

**Comment by BetterAutomations** [comment]
FYI when using `ionic serve` to test in a desktop browser, the port should be 8100.
