### ISSUE TITLE
Safari cannot open the page because the address is invalid.

### ISSUE THREAD

**Issue by jqhoogland** [auth0-samples/auth0-ionic-samples#76]
Logging in seems to work within the browser, but the browser window never closes nor returns authenticated information to the app. 

It seems to be a problem with the redirect uri: `YOUR_PACKAGE_ID://YOUR_DOMAIN/capacitor/YOUR_PACKAGE_ID/callback`

> Might it have something to do with capitalization in the package id? Mine is of the kind `com.BundleIdentifier.AndSuch`

It appears that Auth0 is correctly redirecting me after logout, but then the SFSafariViewController alerts me that: `Safari cannot open the page because the address is invalid.` 

![image](https://user-images.githubusercontent.com/28595964/139683718-fa0655a6-45ad-49ff-a241-8dc40883a05c.png)

Jumping into the developer console, I see that the accompanying href is `about:blank`.

Any ideas?

**Comment by jqhoogland** [comment]
The answer is that my custom url scheme wasn't set up correctly.

Apparently universal links aren't yet supported in SFSafariViewController: https://developer.apple.com/forums/thread/50340.

Well, that was dumb.

**Comment by infinity899** [comment]
I get the same for:

``` `const redirect_uri = ${appId}://${auth0Domain}/capacitor/${appId}/callback` ```
