### ISSUE TITLE
Ionic React ios app callback url

### ISSUE THREAD

**Issue by cstanl16** [auth0-samples/auth0-ionic-samples#79]
I have a web app through ionic that i have setup to work with auth0 and everything works great there but when i have it open through capacitor on ios the callback url isnt working. I changed it to what i thought would be the correct format to match the sample on the quickstart. my app id is: io.app.4155 and the callback url i have been using is:  io.app.4155://{domain}/ionic/io.app.4155/callback

**Comment by patrick-ofallon** [comment]
I am having a similar issue.  It would be nice to have a tutorial for an entire PWA using ionic react and know the appropriate callback structure.

**Comment by ion-labs** [comment]
The same problem for me... callback from auth0 does not work for android (haven't tested it in ios). After login in, the browser (probably capacitor) does not close and shows the error ERR_UNKNOWN_URL_SCHEMA with my callback "[appId]://[my_auth0_domain]/capacitor/[appId]/callback" . Does anybody have resolved the problem?

**Comment by ion-labs** [comment]
I found (so far) a manual solution which requires modification to AndroidManifest.xml file by adding a couple of children tags to <intent-filter> tag
```
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
<data android:scheme="@string/custom_url_scheme" />
```

More details here: [https://capacitorjs.com/docs/apis/app#android](https://capacitorjs.com/docs/apis/app#android)

**Comment by lucax88x** [comment]
Looks like, as today, the problem is still present, was able to fix on Android with comment from @ion-labs but in IOS we still can't figure how to properly configure the callback url.

**Comment by fastluca** [comment]
Hi all, same problem here. Any idea about how to move forward?

**Comment by mikkimichaelis** [comment]
it would appear from the lack of activity on this thread from Auth0 that these issues and repo is of no importance.

**Comment by RobLin72** [comment]
similar issue. 
I logged out the 'isAuthenticated'  initially false as expected 
1. Click the login button, 
2. get the login screen, enter in credentials. 
3. Routes back to the 'login' 'isAuthenticated' is still false. logout button does not appear.
![image](https://user-images.githubusercontent.com/121981680/214357372-8421a540-5e82-4d00-8605-d8a9fe076953.png)
![image](https://user-images.githubusercontent.com/121981680/214357759-811f2ca8-474b-4410-a9a3-3d2264e0ec94.png)
![image](https://user-images.githubusercontent.com/121981680/214357865-38e96bf8-dc97-4b49-abf3-e918636843fc.png)

**Comment by Widcket** [comment]
cc @stevehobbsdev

**Comment by stevehobbsdev** [comment]
@RobLin72 One thing that might cause this is if the **Allowed Web Origins** callback URL is not set correctly in your Auth0 tenant (see [the readme](https://github.com/auth0-samples/auth0-ionic-samples/tree/main/react), this is for React but Angular will be the same).

**Comment by stevehobbsdev** [comment]
> Looks like, as today, the problem is still present, was able to fix on Android with comment from @ion-labs but in IOS we still can't figure how to properly configure the callback url.

@lucax88x Capacitor uses `SFSafariViewController` by default so you may need to [configure the iOS app with a custom scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app).
