### ISSUE TITLE
Login button loops back to login button and does not login

### ISSUE THREAD

**Issue by BetterAutomations** [auth0-samples/auth0-ionic-samples#80]
Following [the tutorial](https://auth0.com/docs/quickstart/native/ionic-angular). When I tap Login, a browser window briefly flashes and it goes back to Login. Tap login again, it just repeats. Happens on both an emulator and a physical phone. I have created a screen recording [here](https://youtu.be/L51jhWeHkys). Here is the [log file](https://pastebin.com/QAPF7yq5).

Might be a CORS issue? I see the following error in the logs. I don't know how to debug CORS issues and the tutorial doesn't mention them.
`2021-11-30 10:08:57.521 5441-5441/com.auth0.samples E/Capacitor/Console: File: http://localhost/home - Line 0 - Msg: Access to XMLHttpRequest at 'https://betterautomations.us.auth0.com/oauth/token' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I am using the following hardware and software:

- Google Pixel 5 emulator running Android 11/API 30
- Samsung Galaxy S6 running Android 11/API 24
- Windows 10 Pro 21H1 development laptop
- Android Studio Android Studio Arctic Fox | 2020.3.1 Patch 3
- Android Gradle Plugin Version 4.1.1
- Gradle Version 7.1.1
- @ionic/angular@5.7.0
- @ionic/core@5.7.0
- @capacitor/cli@3.0.2
- @capacitor/core@3.2.2
- @capacitor/android@3.2.2
- @capacitor/app@1.0.3
- @auth0/auth0-angular@1.6.0
- @auth0/auth0-spa-js@1.17.1
- Node.js 14.17.6

I had mentioned this problem [here](https://github.com/auth0-samples/auth0-ionic-samples/issues/71#issuecomment-940875342) but it went away with PR #77. However, it's back again. I re-downloaded the zip file [per the instructions in the demo](https://auth0.com/docs/quickstart/native/ionic-angular) and it includes that PR. I unzipped it and ran the following commands.
`npm run build`
`npx cap sync`
`npx cap open android`

When that didn't work, I tried changing the port to 8100 in src/app/auth.config.ts and in e2e/protractor.conf.js from the default of 4200. Then re-ran build/sync/open. Angular uses 4200 but Ionic uses 8100. Nonetheless, it did not help. Here is the [log file](https://pastebin.com/QAPF7yq5) from my attempt while using the Pixel 5 emulator.

Here are the settings in my application:
**Application Type:**
Native

**Token Endpoint Authentication Method:**
None

**Application Login URI:**
(Empty)

**Allowed Callback URLs:**
com.auth0.samples://betterautomations.us.auth0.com/capacitor/com.auth0.samples/callback, com.securecoop.app://betterautomations.us.auth0.com/capacitor/com.securecoop.app/callback, http://localhost:8100

**Allowed Logout URLs:**
com.auth0.samples://betterautomations.us.auth0.com/capacitor/com.auth0.samples/callback, com.securecoop.app://betterautomations.us.auth0.com/capacitor/com.securecoop.app/callback, http://localhost:8100

**Allowed Web Origins:**
capacitor://localhost, http://localhost

**Allowed Origins (CORS):**
(Empty)

**Connections:**
Username-Password-Authentication
google-oauth2

**Comment by BetterAutomations** [comment]
Found the problem, it was a CORS issue. I set Allowed Origins (CORS) to include http://localhost. Please consider updating your tutorial documentation.

Fastest issue resolution in history. Hah.

**Comment by Reggino** [comment]
Thanks, this was helping me a lot!

I needed to fill out both "Allowed Web Origins" and "Allowed Origins". 

Please update the documentation accordingly.

**Comment by mediantiba** [comment]
Having the same issue. The required URLs are already set in Allowed Origins (CORS).
