### ISSUE TITLE
UI becomes unresponsive after logout

### ISSUE THREAD

**Issue by mediantiba** [auth0-samples/auth0-ionic-samples#97]
## Summary
I am having an issue when trying to log out from my Ionic app on Android.
```
  logout() {
    // Use the SDK to build the logout URL
    this.auth
      .buildLogoutUrl({ returnTo: environment.auth0.returnTo })
      .pipe(
        tap(async (url) => {
          // Call the logout fuction, but only log out locally
          this.auth.logout({ localOnly: true });
          // Redirect to Auth0 using the Browser plugin, to clear the user's session
          await Browser.open({ url });
          // Navigate back to the login screen
          this.router.navigateByUrl('/login', { replaceUrl: true });
        }),
      )
      .subscribe();
  }
```

The code example from this repository also doesn't work
```
  logout() {
    this.auth
      .buildLogoutUrl({ returnTo: callbackUri })
      .pipe(
        mergeMap(async (url) => {
          await Browser.open({ url, windowName: '_self' });
          this.auth.logout({ localOnly: true });
        })
      )
      .subscribe();
  }
```

## Current behavior
After logging out, the app navigates back to the login page, but the app becomes unresponsive. I cannot log in again until I quit the app.

## Expected behavior
I should be able to log in again after logging out. The app should still be responsive after logging out.

## Platform
Android 11

## Plugins
```
"@capacitor/app": "^1.1.1",
"@capacitor/browser": "^1.0.7",
```

**Comment by crhistianramirez** [comment]
I'm observing the same, logged in angular sdk package: https://github.com/auth0/auth0-angular/issues/258

**Comment by frederikprijck** [comment]
Thanks for reaching out, and apologies for not getting back to you sooner, apparently we have missed this.

I gave this a try using the sample application in this repository, but I am unable to reproduce this. If you believe this is still an issue please let us know and share a reproduction so we can look into it.
